services:
  - type: web
    name: openai-chat-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # bạn sẽ nhập key này bằng tay trong dashboard Render

